# Generated by Django 2.1.5 on 2020-04-08 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_date',
            field=models.DateTimeField(blank=True, verbose_name=datetime.datetime(2020, 4, 8, 16, 11, 5, 743524)),
        ),
    ]
