# Generated by Django 2.2.7 on 2019-12-12 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fbook', '0002_auto_20191212_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_at',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_comments', to='fbook.Messages'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
