# Generated by Django 2.2.7 on 2019-12-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='album_title',
            field=models.TextField(),
        ),
    ]
