# Generated by Django 2.2.7 on 2019-12-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacay', '0002_auto_20191218_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='album_id',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='destination',
            name='album_url',
            field=models.TextField(default=23232),
            preserve_default=False,
        ),
    ]
